# Generated by Django 5.2.7 on 2025-10-31 03:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_code', models.CharField(choices=[('INNOVATION_PROFILE', 'Innovation profile'), ('TECH_PROFILE', 'Tech profile')], max_length=50)),
                ('instrument_version', models.CharField(max_length=20)),
                ('assessment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles_assessments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_assessments', to='core.company')),
            ],
            options={
                'db_table': 'profiles_assessment',
                'ordering': ['-assessment_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_code', models.CharField(choices=[('INNOVATION_PROFILE', 'Innovation profile'), ('TECH_PROFILE', 'Tech profile')], max_length=50)),
                ('instrument_version', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=500)),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('sub_dimension', models.CharField(blank=True, max_length=100)),
                ('level_1_label', models.CharField(blank=True, max_length=400)),
                ('level_2_label', models.CharField(blank=True, max_length=400)),
                ('level_3_label', models.CharField(blank=True, max_length=400)),
                ('level_4_label', models.CharField(blank=True, max_length=400)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profiles_question',
                'ordering': ['instrument_code', 'code'],
                'abstract': False,
                'unique_together': {('instrument_code', 'instrument_version', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observations', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='profiles.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='profiles.question')),
            ],
            options={
                'db_table': 'profiles_response',
                'abstract': False,
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
