# Generated by Django 5.2.7 on 2025-10-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sub_dimension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
