# Generated by Django 5.2.7 on 2025-10-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('tax_id', models.CharField(max_length=64, unique=True, verbose_name='NIT')),
                ('municipality', models.CharField(max_length=128, verbose_name='Municipio')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nombre de contacto')),
                ('contact_role', models.CharField(max_length=128, verbose_name='Cargo del contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Celular de contacto')),
                ('org_type', models.CharField(choices=[('company', 'Empresa'), ('cooperative', 'Cooperativa'), ('association', 'Asociación'), ('foundation', 'Fundación'), ('ngo', 'ONG'), ('public', 'Entidad pública'), ('other', 'Otra')], default='company', max_length=32, verbose_name='Tipo de organización')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la organización')),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_companies', to=settings.AUTH_USER_MODEL, verbose_name='Asesor empresarial')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.organization')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalystCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_companies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysts', to='core.company')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
