# Generated by Django 5.2.7 on 2025-11-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='org_type',
            field=models.CharField(choices=[('organization', 'Organización'), ('entrepreneurship', 'Emprendimiento')], default='organization', max_length=32, verbose_name='Tipo de organización'),
        ),
    ]
