# Generated by Django 5.2.7 on 2025-10-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_origin',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'Nacional'), ('IMPORTED', 'Importado'), ('DONATION', 'Donación'), ('LEASE', 'Leasing / Arrendamiento'), ('IN_HOUSE', 'Fabricación propia'), ('OTHER', 'Otro')], help_text='Selecciona el origen de adquisición del equipo.', max_length=20, null=True, verbose_name='Origen de compra'),
        ),
    ]
